name: Copy value action
description: Propagates an input value to an output.
inputs:
  path:
    description: content to propagate
    required: true
outputs:
  file:
    description: propagated value
    value: ${{ steps.write.outputs.file }}
runs:
  using: composite
  steps:
    - name: Set output
      id: write
      run: echo "file=${{ inputs.path }}" >> "$GITHUB_OUTPUT"
      shell: bash
