name: Copy value action
description: Writes the content of path into the file named by name, and exposes that filename as an output.
inputs:
  path:
    required: true
  name:
    required: true
outputs:
  file:
    value: ${{ steps.write.outputs.file }}
runs:
  using: composite
  steps:
    - name: Write content to file
      id: write
      run: |
        cp "${{ inputs.path }}" ${{ inputs.name }}
        echo "file=${{ inputs.name }}" >> "$GITHUB_OUTPUT"
      shell: bash
