name: Copy value action
description: Writes an input value's content into a named file.
inputs:
  path:
    description: content to write into the file
    required: true
  name:
    required: true
runs:
  using: composite
  steps:
    - name: Write content to file
      run: echo "${{ inputs.path }}" > "${{ inputs.name }}"
      shell: bash
